### PR TITLE
feat(): add rsa pss document hash

### PR DESCRIPTION
**Pull request by zyjblockchain**
The original signature data encapsulation only supports RSA-PKCS algorithm, this PR adds RSA-PSS algorithm, I have tested it and will use it in our production, please pass it. thanks !!!

### CODE REVIEW

**Comment by madestro** [comment]
Hi, we are not sure that we want to add RSA-PSS (that's why we didn't have it already).
By the way, are you aware of this patent? https://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO1&Sect2=HITOFF&d=PALL&p=1&u=%2Fnetahtml%2FPTO%2Fsrchnum.htm&r=1&f=G&l=50&s1=10,735,188.PN.&OS=PN/10,735,188&RS=PN/10,735,188

**Comment by zyjblockchain** [comment]
> Hi, we are not sure that we want to add RSA-PSS (that's why we didn't have it already).
> By the way, are you aware of this patent? https://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO1&Sect2=HITOFF&d=PALL&p=1&u=%2Fnetahtml%2FPTO%2Fsrchnum.htm&r=1&f=G&l=50&s1=10,735,188.PN.&OS=PN/10,735,188&RS=PN/10,735,188

1. I need rsa-pss algorithm to signature some transaction without rsa-pkcs, so I add pss sign document like to pkcs sign document. and I have use this change to our production env.
2. I don't know about the patent sorry. I'm a coder, not a researcher.

**Comment by madestro** [comment]
what i was trying to say is this repository is associated with the patent number 10,735,188, so maybe it is better to tell to your boss to check it before using this signing procedure in production.

**Comment by zyjblockchain** [comment]
> what i was trying to say is this repository is associated with the patent number 10,735,188, so maybe it is better to tell to your boss to check it before using this signing procedure in production.

Does it mean that the current stock is not suitable for use in the production environment due to certain safety risks？
Or need to be run by the patent author to use this code？

**Comment by zyjblockchain** [comment]
why close this pr, I think some people need pss? please

**Pull request closed without merging**
